---
- name: Gather Cisco IOS Interface Details
  hosts: all
  gather_facts: no
  connection: ansible.netcommon.network_cli
  vars:
    ansible_network_os: cisco.ios.ios
    # Force the SSH client to allow the older key exchange algorithm
    ansible_ssh_common_args: '-o KexAlgorithms=+diffie-hellman-group1-sha1'

  tasks:
    - name: Run Show Interface Command
      cisco.ios.ios_command:
        commands:
          - show ip interface brief
      register: interface_output

    - name: Display Interface Details in Semaphore UI Logs
      ansible.builtin.debug:
        msg: "{{ interface_output.stdout_lines }}"
