- name: Configure Cisco IOS Hostname
  hosts: R1
  gather_facts: no
  connection: ansible.netcommon.network_cli
  vars:
    ansible_network_os: cisco.ios.ios

  tasks:
    - name: Run show version to check hardware
      cisco.ios.ios_command:
        commands:
          - show version
      register: final_status

    - name: Configure the hostname
      cisco.ios.ios_config:
        lines:
          - hostname LabRouter01

    - name: Stream Final Status to Semaphore UI Logs
      ansible.builtin.debug:
        msg: "{{ final_status.stdout_lines[0] }}"
