- name: Configure Cisco IOS Hostname
  hosts: R1
  gather_facts: no
  collections:
    - cisco.ios

  tasks:
    - name: Run show version to check hardware
      ios_command:
        commands:
          - show version
        register: final_status

    - name: Configure the hostname
      ios_config:
        lines:
          - hostname LabRouter01

      
      when: "'down' in interface_status.stdout[0]"

    - name: Stream Final Status to Semaphore UI Logs
      ansible.builtin.debug:
        msg: "{{ final_status.stdout_lines[0] }}"
