---
- name: Run Multiple Cisco Commands
  hosts: R1
  gather_facts: no
  connection: ansible.netcommon.network_cli
  vars:
    ansible_network_os: cisco.ios.ios

  tasks:
    - name: Execute Operational Commands on Cisco Device
      cisco.ios.ios_command:
        commands:
          - show ip interface brief
          - show version
      register: device_outputs
    
    - name: Stream Command Results to Semaphore UI Logs
      ansible.builtin.debug:
        msg: 
          - "=================================================="
          - "OUTPUT FOR: show ip interface brief"
          - "=================================================="
          - "{{ device_outputs.stdout_lines[0] }}"
          - ""
          - "=================================================="
          - "OUTPUT FOR: show version"
          - "=================================================="
          - "{{ device_outputs.stdout_lines[1] }}"

    - name: Save Both Outputs into One Local Text File
      ansible.builtin.copy:
        content: |
          === SHOW IP INTERFACE BRIEF ===
          {{ device_outputs.stdout[0] }}

          === SHOW VERSION ===
          {{ device_outputs.stdout[1] }}
        dest: "/opt/semaphore/backup/cisco_devices/{{ inventory_hostname }}_details.txt"
      delegate_to: localhost
