---
- name: Configure Cisco VLAN on the Fly
  hosts: hosts
  gather_facts: false
  connection: ansible.netcommon.network_cli
  vars:
    ansible_network_os: cisco.ios.ios

  tasks:
    - name: Ensure VLAN exists with correct name
      cisco.ios.ios_l3_interfaces:
        state: merged
        config:
          - name: "{{ vlan_name }}"
            ipv4:
              - address: "{{ ip_address_mask }}"
    - name: Step 3 - Ensure the L3 VLAN interfaces are enabled (no shutdown)
      cisco.ios.ios_interfaces:
        state: merged
        config:
          - name: "{{ vlan_name }}"
            description: "{{ vlan_desc }}"
            enabled: true
